knpuniversity/oauth2-client-bundle

Client/OAuth2Client.php
Tests/Client/OAuth2ClientTest.php

Hi,
This PR allow to use scope.
For now, `scopes` was send but it should be `scope`
I test it for github.
https://developer.github.com/v3/oauth/#response
Here documentation from other provider:
- https://developers.facebook.com/docs/reference/javascript/FB.login/v2.5
- https://developer.linkedin.com/docs/oauth2
What do you think ?

Fix scope usage

---

composer.json

> The ^ operator behaves very similarly but it sticks closer to semantic versioning, and will always allow non-breaking updates.

Use '^' instead of '~' for required package versions

---

composer.json

Added the correct `phpunit` and `php-code-coverage` dependencies so everyone can run the tests right out of the box after a fork.

Dev dependencies should include the compatible PHPunit version

---

README.md
composer.json
src/Client/Provider/BitbucketClient.php
src/DependencyInjection/KnpUOAuth2ClientExtension.php
src/DependencyInjection/Providers/BitbucketProviderConfigurator.php
tests/Client/OAuth2ClientTest.php
tests/FunctionalTest.php
tests/Security/Authenticator/SocialAuthenticatorTest.php
tests/Security/Exception/FinishRegistrationExceptionTest.php
tests/Security/Exception/NoAuthCodeAuthenticationExceptionTest.php
tests/Security/Helper/FinishRegistrationBehaviorTest.php
tests/Security/Helper/PreviousUrlHelperTest.php

OAuth Bitbucket Client added, tests added

Bitbucket Client added

---

src/Client/Provider/VKontakteClient.php
src/DependencyInjection/KnpUOAuth2ClientExtension.php
src/DependencyInjection/Providers/VKontakteProviderConfigurator.php

for issue #7 VKontakte provider added.

VKontakte provider added

---

README.md
src/Client/Provider/OdnoklassnikiClient.php
src/Client/Provider/SlackClient.php
src/Client/Provider/VimeoClient.php
src/Client/Provider/YahooClient.php
src/Client/Provider/YandexClient.php
src/DependencyInjection/KnpUOAuth2ClientExtension.php
src/DependencyInjection/Providers/OdnoklassnikiProviderConfigurator.php
src/DependencyInjection/Providers/SlackProviderConfigurator.php
src/DependencyInjection/Providers/VimeoProviderConfigurator.php
src/DependencyInjection/Providers/YahooProviderConfigurator.php
src/DependencyInjection/Providers/YandexProviderConfigurator.php

my opinion is that config.yml code becomes too long for readme file. It would be great to create a separate file with all configuration options

added Odnoklassniki, Slack, Vimeo, Yahoo and Yandex providers

---

composer.json

Allow installing the new OAuth client 2.x in dependencies

---

src/DependencyInjection/Providers/GoogleProviderConfigurator.php

Avoid notice `Undefined index: access_type` on [this line](https://github.com/knpuniversity/oauth2-client-bundle/tree/ad82b0f780e1ad54dd7de2d353027d8384891080/src/DependencyInjection/Providers/GoogleProviderConfigurator.php#L44) when optional configuration is not given

Fix optional configuration in Google provider

---

src/DependencyInjection/Providers/GoogleProviderConfigurator.php

Making sure that if config is *not* specified, that we don't include it in the request!
See #53

[Google] Fixing undefined array indexes + extra request data

---

src/Resources/config/services.xml

As of Symfony 3.3, autowire_types is deprecated.
This adds an alias for the knpu.oauth2.registry service definition.

Update service definition for autowiring

---

src/DependencyInjection/KnpUOAuth2ClientExtension.php
tests/DependencyInjection/KnpUOAuth2ClientExtensionTest.php

Fix #60 
I feel like the _service Id_ and _alias name_ are inverted, but tests does not pass if I do it the other way around

Set an alias to every client service

---

README.md
src/Client/Provider/KeycloakClient.php
src/Client/Provider/MollieClient.php
src/Client/Provider/PsnClient.php
src/Client/Provider/SalesforceClient.php
src/Client/Provider/StravaClient.php
src/Client/Provider/UberClient.php
src/Client/Provider/UnsplashClient.php
src/Client/Provider/ZendeskClient.php
src/DependencyInjection/KnpUOAuth2ClientExtension.php
src/DependencyInjection/Providers/KeycloakProviderConfigurator.php
src/DependencyInjection/Providers/MollieProviderConfigurator.php
src/DependencyInjection/Providers/PsnProviderConfigurator.php
src/DependencyInjection/Providers/SalesforceProviderConfigurator.php
src/DependencyInjection/Providers/StravaProviderConfigurator.php
src/DependencyInjection/Providers/UberProviderConfigurator.php
src/DependencyInjection/Providers/UnsplashProviderConfigurator.php
src/DependencyInjection/Providers/ZendeskProviderConfigurator.php

Another portion of clients: Salesforce, Zendesk, Strava, Uber, Unsplash, PSN, Mollie are added

New clients added

---

README.md
src/Resources/config/services.xml
src/Security/User/OAuthUser.php
src/Security/User/OAuthUserProvider.php
tests/Security/User/OAuthUserProviderTest.php
tests/Security/User/OAuthUserTest.php

This add a user provider that can be used for simple authentication use cases, allowing any successful OAuth to authenticate into your app without any persistence.
(This is similar to [the other bundle](https://github.com/hwi/HWIOAuthBundle/blob/8a97b6b2ba0be0064c9616a3cfc14c2c0d8a589b/Security/Core/User/OAuthUserProvider.php).)

Add simple user provider

---

src/Client/Provider/GitlabClient.php

Note: You should use a tool like PHPStan to prevent this kind of issue. ;-)

Fix missing GitlabResourceOwner namespace use

---

src/Security/Authenticator/SocialAuthenticator.php
src/Security/Exception/IdentityProviderAuthenticationException.php
src/Security/Exception/InvalidStateAuthenticationException.php

Fixes #78 
The entire point of `fetchAccessToken()` is to help catch as many "normal" errors as possible and turn them into proper "AuthenticationException" situations with decent messages.

Catching 2 other common authentication errors

---

README.md
src/Client/Provider/DiscordClient.php
src/DependencyInjection/Providers/DiscordProviderConfigurator.php

Because the previous library is only compatible with the ultra old `thephpleague/oauth2-client` in version` 1.x`.
The documentation no longer reference the library `https://github.com/teamreflex/oauth2-discord`. Instead, they promote https://github.com/wohali/oauth2-discord-new.
See: http://oauth2-client.thephpleague.com/providers/thirdparty/

Change underlying library for discord because it's not compliant with oauth2-client v2.x

---

README.md

With https://github.com/knpuniversity/oauth2-client-bundle/pull/79 the docs is not longer working for lower than symfony 3.4. So a hint should be added how to get it work with <3.4

Add hint to call supports in getCredentials method for symfony lower than 3.4

---

CHANGELOG.md
README.md
bin/update_readme
src/DependencyInjection/Providers/FacebookProviderConfigurator.php

We defaulted the `graph_api_version` before to 2.5. That's not a good idea: the user *really* needs to specify this. Now it will be required (small BC break, but they will see it as a huge error immediately).
Also tweaked the README generator a bit. Other README changes are related to recent changes (and generated by `update_readme`).

Updating Facebook graph version to show 1.12 & not have a default

---

src/Client/OAuth2Client.php
tests/Client/OAuth2ClientTest.php

This removes the state from the session once it's read, as it's no longer needed.

Remove state from the session

---

src/DependencyInjection/Providers/GoogleProviderConfigurator.php

The PHP league Google client has an option named useOidcMode which this PR lets you set in this bundle configuration.
See https://github.com/thephpleague/oauth2-google#resource-owner-attributes

Add configurable option to use oidc mode for the Google Provider

---

README.md
src/DependencyInjection/Providers/Auth0ProviderConfigurator.php

Add mandatory config key 'account' for Auth0
Update README
Requested in #104

Missing config key for Auth0

---

README.md
bin/update_readme

Update docs to refer to the symfony recipe-contrib.
Update references to yaml configs.
Use env vars instead of parameters.yml.
Update interfaces for autowiring.
Requested in #112

Update documentation to use symfony flex recipe

---

README.md

Fixes the knpuniversity.com link to point to symfonycasts.com screencast on symfony-security. Also adds the URL protocol since current link results in a 404 on Github

Fix README link to "Guard authenticator" screencast

---

src/DependencyInjection/Configuration.php
src/DependencyInjection/KnpUOAuth2ClientExtension.php

Symfony 4.2 asks for the tree builder root to be defined in the construct of the TreeBuilder.  This change ensures backwards compatibilty and allows correct operation with future Symfony framework versions.

Update DependencyInjection to account for changes in Symfony 4.2

---

README.md
src/DependencyInjection/Providers/LinkedInProviderConfigurator.php

Hi,
I ran into some issues implementing Linkedin OAuth, basically because:
1. Linkedin is switching from v1 to v2 of their APIs, and there is no way to specify version to use from this bundle. Since all new Linkedin API project cannot use v1, OAuth is unusable with this bundle. PHPLeague oauth2-linkedin provider provide a withResourceOwnerVersion() method since 4.1.0 to set version to use, and I'm planning to submit a PR with this feature in this repo, but said that, I must take one thing at a time :)
2. In conjunction of their version upgrade, Linkedin enforced their policy, and some of the default fields retrieved from PHPLeague provider are now forbidden without requesting developer authorization, so after authentication, it's all 403 responses (=> "Not enough permissions to access: …

Adding "api_version" and "fields" options for Linkedin's provider

---

README.md
bin/update_readme

What about to use `NULL` instead of empty strings? It's clearer I think because in config definition we use `defaultNull()` calls for it.

 Use NULL instead of empty string for defaultNull() values in README

---

.travis.yml

This will help us to catch inconsistence in README on CI level. No more missing call of `bin/update_readme`!
The build should be green after #171 is merged

Fail CI if repo is in dirty state after bin/update_readme

---

README.md

In the readme there is this example:
```
// get the user directly
$user = $client->fetchUser();
// get the access token and then user
$accessToken = $client->getAccessToken();
$user = $client->fetchUserFromToken($accessToken);
```
What's not quite obvious to the untrained eye in my opinion is that you cannot execute the example code exactly like this, because `$client->fetchUser()` "burns" the authorization code so you cannot use it again in `$client->getAccessToken()`. The OAuth2 server will report an error "code is invalid or expired".
A simple "OR" in the comment should make it more clear that both ways of acquiring the user data are mutually exclusive in the example and not to be executed one after the other.
```
// get the user directly
$user = $client->fetchUser();
// OR: get the …
```

Clarified ambiguous example in the readme

---

README.md

Classname for Facebook Authenticator in security.yaml seems to have an errata

Errata in classname for authenticator

---

.travis.yml
bin/update_readme
composer.json
tests/DependencyInjection/ConfigurationTest.php
tests/Security/Authenticator/SocialAuthenticatorTest.php
tests/Security/User/OAuthUserProviderTest.php

Hi!
This removes support for PHP 5.6, 5.7 and 7.0, which are EOL and also removes support for all Symfony versions before 3.4. This will be included in the next minor version, so it simply means that you need to be on an actively maintained version of Symfony and PHP in order to update from here.
Cheers!

Bumping minimum php version to 7.1 and removing support for EOL Symfony versions

---

.travis.yml
composer.json
phpstan.neon.dist

See issue #88 
Here's a first try to integrate phpstan :)
With the higher phpstan level (the higher the stricter), i.e. 7, there is at this moment 221 errors detected.
Not all of them are relevant IMHO.
For instance there is a lot of "errors" like ` Return typehint of method KnpU\OAuth2ClientBundle\Client\Provider\SlackClient::fetchUserFromToken() has invalid type AdamPaterson\OAuth2\Client\Provider\SlackResourceOwner.` that could be ignore.
I'd like to have opinion of others about how to proceed about the detected errors.
Do we handle them in this PR?
Which errors should be ignored?
Should we decrease the phpstan level at first and increase it little by little?

add phpstan check to ci

---

src/DependencyInjection/Configuration.php

Assuming two different config files:
```yaml
knpu_oauth2_client:
clients:
drupal:
client_id: foo
client_secret: foo
type: drupal
redirect_route: foo
base_url: foo
```
```yaml
imports:
- { resource: config.yml }
knpu_oauth2_client:
clients:
drupal:
client_id: bar
```
This will cause an `InvalidConfigurationException`:
```
Unrecognized option "0" under "knpu_oauth2_client/clients/drupal"
```
This PR fixes this error and allows overriding parts of the configuration.
(See https://github.com/symfony/symfony/issues/12304#issuecomment-63910362 for a more detailed explanation.)

Allow overriding parts of a client config

---

README.md
src/DependencyInjection/Providers/Auth0ProviderConfigurator.php

This PR makes possible to use the the auth0 client library with a custom domain setting.
It depends on this PR in the client library: https://github.com/RiskioFr/oauth2-auth0/pull/16
The `account` parameter is not required anymore, as the `custom_domain` parameter takes priority if it's set. It is implemented in a backward compatible way.

added the custom_domain parameter to the auth0 client library config

---

src/Client/ClientRegistry.php

The client registry should allow any OAuth2ClientInterface implementation.
Fixes and error introduced in https://github.com/knpuniversity/oauth2-client-bundle/commit/61af3d7c7510e5f51537d3895e239aec87860c98 similar to #159.

Allow any OAuth2ClientInterface implementation in ClientRegistry

---

README.md
src/Client/Provider/AppleClient.php
src/DependencyInjection/KnpUOAuth2ClientExtension.php
src/DependencyInjection/Providers/AppleProviderConfigurator.php

Adds support for [oauth-apple](https://github.com/patrickbussmann/oauth2-apple)

Oauth apple support

---

.gitignore
src/Client/OAuth2Client.php
src/Client/OAuth2ClientInterface.php
src/Security/Authenticator/SocialAuthenticator.php
tests/Client/OAuth2ClientTest.php
tests/Security/Authenticator/SocialAuthenticatorTest.php

This little change allow to pass `options` when fetching `AccessToken`. 
Some providers checks for `redirect_uri` when fetching token from `code` (last step). When in my app is more than one entry point with otuah (for example different scopes in different app region) I want to have ability to change `redirect_uri`. The `redirect` method allows for that, but then, when user returns from provider `redirect_uri` param is taken from main configuration, which causes auth error (i.e. GitLab). For now the only solution is:
```
gitlab-register:
type: gitlab
client_id: '%env(OAUTH_GITLAB_CLIENT_ID)%'
client_secret: '%env(OAUTH_GITLAB_CLIENT_SECRET)%'
redirect_route: register_gitlab_check
gitlab-auth:
type: gitlab
client_id: '%env(OAUTH_GITLAB_CLIENT_ID)%'
client_secret: …
```

Allow to pass options when fetching access token

---

composer.json
src/Client/OAuth2Client.php

Fixes #232
This also drops support for older Symfony versions. This will be for v2.
TODO: Add a CHANGELOG.

Adding OAuth2Client::isStateless() hook point

---

.travis.yml
README.md
src/Client/Provider/BuddyClient.php
src/DependencyInjection/KnpUOAuth2ClientExtension.php
src/DependencyInjection/Providers/BuddyProviderConfigurator.php

Add Buddy client

---

README.md

I have symfony 4.3, so can't install this package and i only saw there was a minimum version during composer install :(

List required symfony version

---

README.md
src/DependencyInjection/Providers/AzureProviderConfigurator.php

With this release https://github.com/TheNetworg/oauth2-azure/releases/tag/v2.0.0, we gain the support for v2.0 of Azure endpoints (see https://github.com/TheNetworg/oauth2-azure/pull/76).
One thing that's missing with this bundle, is the chance to set the default_end_point_version in order to switch from 1 to 2.
I've done this little PR in order to make it possible.
Is worthy to notice that I've left `1.0` as `default_end_point_version value` in order to not introduce a BC break (with `TheNetworg/oauth2-azure` we use to go directly on 1.0).
WDYT?

Added support for endpoint version on Azure provider

---

src/DependencyInjection/Providers/AzureProviderConfigurator.php

I don't know much about this provider, but this value should either be required or have a default. It appears that the underlying library defaults to 1.6 - https://github.com/TheNetworg/oauth2-azure/blob/0d28aaa681d1044525418c27843f65d7946f67c6/src/Provider/Azure.php#L38

Adds a default value to azure api_version

---

README.md
src/Client/OAuth2Client.php
src/Client/OAuth2ClientInterface.php
tests/Client/OAuth2ClientTest.php

As discussed in #260, it would be great to have native support to refresh access tokens. I'm successfully using this in my Symfony 4.4 application.
Closes: #260

Add support for refreshToken()

---

README.md

Travis is no longer used for CI. Omitting the GH Actions badge for consistency with the other Symfony Bundles.

remove travis status badge

---

.flintci.yml

It does not appear FlintCI is being maintained anymore based on the activity in the GitLab repo. Furthermore, with GitHub Actions - additional CI just complicates life.

[ci] drop FlintCI from CI

---

src/Client/Provider/TwitchClient.php

The tpavlek/oauth2-twitch provider returns a [TwitchUser](https://github.com/tpavlek/oauth2-twitch/blob/master/src/Entity/TwitchUser.php) entity.

Update TwitchClient configuration

---

src/Security/User/OAuthUser.php
tests/Security/Authenticator/SocialAuthenticatorTest.php
tests/Security/User/OAuthUserTest.php
tests/app/TestKernel.php

With this, we should get rid of deprecations introduced with symfony 5.*
I've checked all the changelogs and latest test https://github.com/knpuniversity/oauth2-client-bundle/runs/3484375665
We should be compliant.

Removed some deprecations introduced in Symfony 5.*

---

.github/workflows/ci.yaml
.github/workflows/static-analysis.yaml
CHANGELOG.md
README.md
composer.json
phpunit.xml.dist
src/Security/Exception/IdentityProviderAuthenticationException.php
src/Security/User/OAuthUser.php
src/Security/User/OAuthUserProvider.php
tests/Client/ClientRegistryTest.php
tests/Client/OAuth2ClientTest.php
tests/Security/Authenticator/OAuth2AuthenticatorTest.php
tests/Security/Authenticator/SocialAuthenticatorTest.php
tests/Security/Helper/FinishRegistrationBehaviorTest.php
tests/Security/Helper/HelperTestMockBuilderTrait.php
tests/Security/Helper/PreviousUrlHelperTest.php
tests/Security/Helper/SaveAuthFailureMessageTest.php
tests/allowed.json

~TODO: remove (at least) php-cs-fixer so that Symfony 6 is used in tests.~

Enhancing test matrix, Symfony 6 support, dropping PHP 7.1, client 1.0

---

README.md

Instead of scrolling to the generic provider segment, link will make it easier.

Add link to Generic Provider

---

README.md

It would be good to ask to double-check that official list first if there's no provider users are looking for in our table.

Add a link to the full list of clients from PHP League

---

README.md
src/Client/Provider/TwitchHelixClient.php
src/DependencyInjection/KnpUOAuth2ClientExtension.php
src/DependencyInjection/Providers/TwitchHelixProviderConfigurator.php
src/DependencyInjection/Providers/TwitchProviderConfigurator.php

Added support for the vertisan/oauth2-twitch-helix bundle

Twitch helix support

---

src/DependencyInjection/KnpUOAuth2ClientExtension.php

The error message currently lists the class names, but the configuration needs the keys.

Fix an error message

---

README.md
src/DependencyInjection/Providers/GeocachingProviderConfigurator.php

As best I can tell, the `start()` method is still required to automatically redirect to the "login" page when accessing a protected resource. This PR copies its use from the Guard Authenticator to the Symfony Authenticator section.

[docs]: Add entrypoint functionality to Authenticator docs

---

src/DependencyInjection/ProviderFactory.php
tests/DependencyInjection/ProviderFactoryTest.php

The functionality “Fetching access keys via OAuth2 to be used with an API” mentioned in the README does not necessarily need a `redirect_url`, thus providing it should not be mandatory. We have an Endpoint (pingen.com) which does not allow `redirect_url` to be sent in these cases. Also, it wouldn't make much sense if it did because the route must be a valid symfony route, which in some cases must be created without a use.
I also think it makes sense to allow `null` here because this parameter isn't mandatory in the `League\OAuth2\Client\ProviderAbstractProvider` (https://github.com/thephpleague/oauth2-client/blob/master/src/Provider/AbstractProvider.php#L454).

Allow null as redirect_route

---

src/DependencyInjection/Providers/KeycloakProviderConfigurator.php

KeycloakProviderConfigurator.getProviderOptions() : add version to returned options array

KeycloakProviderConfigurator.getProviderOptions() : add version to returned options array

---

src/DependencyInjection/Providers/KeycloakProviderConfigurator.php

Set Keycloak provider's 'version' config option to null by default

---

README.md
src/Client/Provider/WebflowClient.php
src/DependencyInjection/KnpUOAuth2ClientExtension.php
src/DependencyInjection/Providers/WebflowProviderConfigurator.php

This PR adds an implmentation for the new [`koalati/oauth2-webflow`](https://github.com/koalatiapp/oauth2-webflow) OAuth 2.0 provider for [Webflow](https://webflow.com/).

feat: add Webflow provider

---

.github/workflows/ci.yaml
src/DependencyInjection/ProviderFactory.php
src/DependencyInjection/Providers/SpotifyProviderConfigurator.php
src/Security/Exception/FinishRegistrationException.php
src/Security/Helper/FinishRegistrationBehavior.php

After some changes upstream in GitHub CI config: https://github.com/SymfonyCasts/.github/pull/2

Rebuild CI and fix CS

---

README.md
phpstan.neon.dist
src/Client/Provider/PassageClient.php
src/DependencyInjection/KnpUOAuth2ClientExtension.php
src/DependencyInjection/ProviderFactory.php
src/DependencyInjection/Providers/PassageProviderConfiguration.php
src/Security/Exception/FinishRegistrationException.php

I missed an implementation of [Passage](https://passage.1password.com/) from 1Password that supports [Passkeys](https://passkeys.directory/).
So I've implemented it myself. 
Feel free to send me some feedback also for my first own package [malteschlueter/oauth2-passage](https://github.com/malteschlueter/oauth2-passage) package.
What minimum PHP version should the [malteschlueter/oauth2-passage](https://github.com/malteschlueter/oauth2-passage) package support? The same as this package `>=7.4`?

Add new provider Passage

---

README.md

.env.dist was dropped in 2018.
https://symfony.com/blog/improvements-to-the-handling-of-env-files-for-all-symfony-versions
#434

drop reference to .env.dist

---

README.md

Since this bundle requires at least Symfony 4, no reason to keep the documentation for Symfony 3.

drop reference to Symfony 3

---

composer.json

- Removes support for Symfony 4.x
- Bumps minimum supported Symfony version to `5.4`
- fixes incorrect `symfony/security-guard` constraint (version 6+ doesn't exist)

drop Symfony 4.x support

---

src/DependencyInjection/KnpUOAuth2ClientExtension.php

Fix deprecation ([issue 447](https://github.com/knpuniversity/oauth2-client-bundle/issues/447))
_The "Symfony\Component\HttpKernel\DependencyInjection\Extension" class is considered internal since Symfony 7.1, to be deprecated in 8.1; use Symfony\Component\DependencyInjection\Extension\Extension instead. It may change without further notice. You should not use it from "KnpU\OAuth2ClientBundle\DependencyInjection\KnpUOAuth2ClientExtension"._

Fix Symfony 7.1 deprecation for Extension

---

tests/Client/ClientRegistryTest.php
tests/Security/Authenticator/SocialAuthenticatorTest.php

- can drop legacy annotations once guard authenticators are no longer used
- fixes `start()` method signature in test fixture to match its respective interface

[ci] tag test as legacy due to deprecation notice

---

src/DependencyInjection/ProviderFactory.php
tests/DependencyInjection/ProviderFactoryTest.php

**Problem Description:**
In the current implementation of the createProvider method in the ProviderFactory class, any redirectUri is processed via Symfony's UrlGeneratorInterface::generate. This causes an issue when an absolute URL (external link), such as https://external-site.com/callback, is passed, since generate is only meant to work with Symfony routes. As a result, an error is thrown when trying to handle external URLs. It could be inconvenient if you work with react apps. 
**Solution:**
This feature adds a check to the createProvider method to differentiate between internal routes and external URLs. If the redirectUri is an absolute URL (determined using filter_var with FILTER_VALIDATE_URL), the URL is used directly without invoking the generate method. This prevents calling the …

fix: Handle external URLs correctly in ProviderFactory (Fixes external redirect URL handling)
