DependencyInjection/KnpUOAuth2ClientExtension.php
DependencyInjection/Providers/LinkedInProviderConfigurator.php
README.md

for #7 
Also if we can create new wiki i can added linkedin usage sample too.

LinkedIn Provider Added

---

DependencyInjection/KnpUOAuth2ClientExtension.php
DependencyInjection/Providers/VkProviderConfigurator.php
README.md

For #7
This new custom providers system is pure awesomeness! Thanks, Ryan!
EvE Online provider is en route aswell.

VK.com Provider added

---

DependencyInjection/KnpUOAuth2ClientExtension.php
DependencyInjection/Providers/GoogleProviderConfigurator.php
README.md

for #7
Google Provider added also i change duplicate connectAction method.

Google Provider Added

---

DependencyInjection/KnpUOAuth2ClientExtension.php
DependencyInjection/Providers/EveOnlineProviderConfigurator.php

Add Eve Online provider

---

Client/Provider/InstagramClient.php
DependencyInjection/KnpUOAuth2ClientExtension.php
DependencyInjection/Providers/InstagramProviderConfigurator.php
README.md
composer.json

Add Instagram provider

---

Client/Provider/GitlabClient.php
DependencyInjection/KnpUOAuth2ClientExtension.php
DependencyInjection/Providers/GitlabProviderConfigurator.php
README.md

Both self-hosted and Gitlab.com supported.

Added native support for Gitlab

---

src/Client/OAuth2Client.php
tests/Client/OAuth2ClientTest.php
tests/app/TestKernel.php

[#43] Making the redirect() options configurable

---

.travis.yml

... and dropping PHP HHVM support

Fixing tests

---

composer.json

Let's see if we support Symfony4!

---

src/DependencyInjection/KnpUOAuth2ClientExtension.php
src/Resources/config/services.xml

This should fix the Symfony 4 failing tests :)

Making services explicitly public so that they remain public in Symfony 4

---

README.md
src/Client/Provider/BoxClient.php
src/Client/Provider/BufferClient.php
src/Client/Provider/CanvasLMSClient.php
src/Client/Provider/CleverClient.php
src/Client/Provider/DevianArtClient.php
src/Client/Provider/DiscordClient.php
src/Client/Provider/ElanceClient.php
src/Client/Provider/EventbriteClient.php
src/Client/Provider/FoursquareClient.php
src/Client/Provider/MailRuClient.php
src/DependencyInjection/KnpUOAuth2ClientExtension.php
src/DependencyInjection/Providers/BoxProviderConfigurator.php
src/DependencyInjection/Providers/BufferProviderConfigurator.php
src/DependencyInjection/Providers/CanvasLMSProviderConfigurator.php
src/DependencyInjection/Providers/CleverProviderConfigurator.php
src/DependencyInjection/Providers/DevianArtProviderConfigurator.php
src/DependencyInjection/Providers/DiscordProviderConfigurator.php
src/DependencyInjection/Providers/ElanceProviderConfigurator.php
src/DependencyInjection/Providers/EventbriteProviderConfigurator.php
src/DependencyInjection/Providers/FoursquareProviderConfigurator.php
src/DependencyInjection/Providers/MailRuProviderConfigurator.php

Let's increase the number to 45 ;)
Box, Buffer, CanvasLMS, Clever, DevianArt, Discord, Elance, Eventbrite, Foursquare and Mail.Ru are added
I use this list of providers [http://oauth2-client.thephpleague.com/providers/thirdparty/](url).
Maybe you have another one? Thx

Ten more clients added 

---

README.md

Updating Guard docs for Sf4 support

---

README.md

Feel free to edit and fix my English 😄 
Also, I didn't want to write something like `Ideally this bundle is eventually going to be replaced by hwi/oauth-bundle` because I don't know your plans for it. But you might want to add some words about the future of it.

Added a hint about the relation to hwi/oauth-bundle

---

.flintci.yml

I took my time, I have to admit it. :wink: 
But as you requested, here is a pull request to integrate FlintCI. :tada: 
To make it working, you have to log-in and setup the repository: https://flintci.io/docs#getting-started
As you can see, the configuration file is quite simple. You just have to enable the services you want!
I just enable php-cs-fixer for now, but you can take a look at the other available services: https://flintci.io/docs#services
I will really appreciate some feedback, don't hesitate to give me some on Slack. :wink:

FlintCI integration

---

src/Security/Exception/IdentityProviderAuthenticationException.php

Using simpler getMessage(), which is identical

---

src/DependencyInjection/Configuration.php
src/DependencyInjection/KnpUOAuth2ClientExtension.php
src/DependencyInjection/ProviderFactory.php
tests/DependencyInjection/ConfigurationTest.php
tests/DependencyInjection/KnpUOAuth2ClientExtensionTest.php
tests/FunctionalTest.php
tests/app/TestKernel.php

Make http client configurable

---

README.md
src/DependencyInjection/Providers/AzureProviderConfigurator.php

Adds all configurable vars to tree builder.
https://github.com/knpuniversity/oauth2-client-bundle/issues/130

Adds whole config for azure

---

README.md
src/Client/Provider/GeocachingClient.php
src/DependencyInjection/KnpUOAuth2ClientExtension.php
src/DependencyInjection/Providers/GeocachingProviderConfigurator.php

Hello,
Here the client Geocaching for geocaching.com!

Add Geocaching Client

---

src/Security/Authenticator/SocialAuthenticator.php

Allow any OAuth2ClientInterface implementation in SocialAuthenticator

---

README.md

After running `bin/update_readme` the repo is in a dirty state, this PR fixes it.
P.S. I opened #173 to prevent such cases.

Tweak README with bin/update_readme command

---

src/Client/ClientRegistry.php

See #194 for further information.

Allow To Retrieve Enabled Client Keys

---

composer.json

Fixing bad require - should be in require-dev

---

README.md
bin/update_readme

No more empty lines for missing optional config :)

Get rid of empty lines for optional config in README

---

README.md
bin/update_readme

Hi. I updated bin/update_readme to fit current Symfony versions and re-generated README.md file applying these changes. Also I included PR #226 as there is no sense to update README.md file only.

Updates to bin/update_readme script to fit current Symfony version

---

README.md
src/Client/Provider/WaveClient.php
src/DependencyInjection/KnpUOAuth2ClientExtension.php
src/DependencyInjection/Providers/WaveProviderConfigurator.php

Wave is a free invoicing & accounting software with credit card processing & payroll services for small businesses. https://www.waveapps.com

Add Wave OAuth2 Provider

---

README.md
src/Client/Provider/SymfonyConnectClient.php
src/DependencyInjection/KnpUOAuth2ClientExtension.php
src/DependencyInjection/Providers/SymfonyConnectProviderConfigurator.php

Add [SymfonyConnect](https://connect.symfony.com) provider ☺️

Add SymfonyConnect provider

---

src/Client/OAuth2Client.php

Look for both POST and GET params when getting state

---

README.md
src/Client/Provider/TwitchClient.php
src/DependencyInjection/KnpUOAuth2ClientExtension.php
src/DependencyInjection/Providers/TwitchProviderConfigurator.php

add twitch provider

---

tests/Client/ClientRegistryTest.php
tests/Client/OAuth2ClientTest.php
tests/Client/Provider/BatchProviderTest.php
tests/DependencyInjection/ProviderFactoryTest.php
tests/KnpUOAuth2ClientBundleTest.php
tests/Security/Authenticator/SocialAuthenticatorTest.php
tests/Security/Exception/FinishRegistrationExceptionTest.php
tests/Security/Exception/IdentityProviderAuthenticationExceptionTest.php
tests/Security/Exception/InvalidStateAuthenticationExceptionTest.php
tests/Security/Helper/FinishRegistrationBehaviorTest.php
tests/Security/Helper/HelperTestMockBuilderTrait.php
tests/Security/Helper/SaveAuthFailureMessageTest.php

While investigating an edge case I have where the redirect_uri isn't being generated properly (still doing some troubleshooting before I raise an issue) I started looking through the tests for the package and saw there were some chunks that weren't under test.  I figured I would spend some time writing additional tests for exercise.

Improve test coverage

---

src/DependencyInjection/KnpUOAuth2ClientExtension.php
tests/DependencyInjection/KnpUOAuth2ClientExtensionTest.php

Add specific message when a generic client has configured a provider_class that does not exist.
resolves #222

Add specific error message.

---

README.md

Adding missing use_state option to generic docs

---

.travis.yml
composer.json
tests/DependencyInjection/KnpUOAuth2ClientExtensionTest.php

Hello! This PR proposes to allow the installation of this package on php 8 because it seems to work. It also extends the Travis configuration to make sure that the project is tested on php 8.
Fixes #275

Allow the installation on php 8

---

README.md

Fixing broken link according to https://github.com/knpuniversity/oauth2-client-bundle/issues/297

Fixing broken link in README.me

---

README.md

Precision about the value of proxy in the settings

---

bin/update_readme

Actually, changes in #352 ahd to be done in bin/update_readme . I ported that change there in this PR :)

Fix README generation after bin/update_readme run

---

README.md
bin/update_readme

Changes in #345 had to be done in bin/update_readme instead - I fixes this

Fix autogenerated README - proxy comment

---

README.md

In order to match: https://github.com/knpuniversity/oauth2-client-bundle/blob/24baf0d2e62a732be52eacc445eb50ab65383107/composer.json#L16

Remove Requirements section completely

---

CHANGELOG.md

Hi OAuth2'ers!
This release adds support for Twitch Helix thanks to @ErdemUyanik & @bocharsky-bw!
Diff: https://github.com/knpuniversity/oauth2-client-bundle/compare/v2.9.0...v2.10.0
Happy authenticating!
---
*February 23rd, 2022*
- [#361](https://github.com/knpuniversity/oauth2-client-bundle/pull/361) - Twitch helix support - *@ErdemUyanik*

[release] v2.10.0

---

CHANGELOG.md

*May 24th, 2022*
- [#369](https://github.com/knpuniversity/oauth2-client-bundle/pull/369) - Fix an error message - *@fabpot*
_Generated by Git Released_

[git-released] v2.10.1

---

src/Client/OAuth2PKCEClient.php
tests/Client/OAuth2PKCEClientTest.php

Apply changes required by PHP CS Fixer and fix PHP 8.2 build

---

tests/app/TestKernel.php

In order to fix the deprecation message in #395

Add void return type for registerContainerConfiguration()

---

src/Client/OAuth2PKCEClient.php

Fix broken CS

---

README.md
src/Client/Provider/DisqusClient.php
src/DependencyInjection/KnpUOAuth2ClientExtension.php
src/DependencyInjection/Providers/DisqusProviderConfigurator.php

New [Disqus](https://disqus.com) provider integration, [`antalaron/oauth2-disqus`](https://github.com/antalaron/oauth2-disqus)

Add Disqus provider

---

src/Client/OAuth2ClientInterface.php
src/DependencyInjection/ProviderFactory.php
src/Security/Exception/FinishRegistrationException.php
src/Security/Helper/SaveAuthFailureMessage.php

Fix `SaveAuthFailureMessage` trait for symfony 7

hf: symfony 7
